version: "3.8"

services:
  # ─────────────────── Front
  frontend:
    build: ./frontend
    image: transcendence_frontend
    ports: ["3001:80"]  # LOCAL TESTING
    restart: unless-stopped
    networks: [transcendence]

  # ─────────────────── Back
  backend:
    build: ./backend
    image: transcendence_backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:?set in .env}
      - DATABASE_URL=file:/data/db.sqlite
    volumes: ["db-data:/data"]
    ports: ["3000:3000"] # DEV CHECK
    restart: unless-stopped
    networks: [transcendence]

  # ─────────────────── Admin (PHP)
  admin:
    build: ./admin
    image: transcendence_admin
    ports: ["9000:80"]
    restart: unless-stopped
    networks: [transcendence]

  # ─────────────────── Nginx Gateway
  nginx:
    build: { context: ./nginx }
    image: transcendence_gateway
    depends_on: [frontend, backend, admin]
    ports: ["80:80"]
    restart: unless-stopped
    networks: [transcendence]

volumes:
  db-data:

networks:
  transcendence:
    driver: bridge
