# docker-compose.yaml

version: "3.8"

services:
  # ─────────────────── Front
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        - VITE_API_URL=https://transcendence.${LOCAL_IP}.nip.io:8443
    image: transcendence_frontend
    ports: ["3001:3001"]
    restart: unless-stopped
    networks: [ts_transcendence]
    environment:
      - VITE_API_URL=https://transcendence.${LOCAL_IP}.nip.io:8443

  # ─────────────────── Back
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    image: transcendence_backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_URL=https://transcendence.${LOCAL_IP}.nip.io:8443
      - FRONTEND_URL=https://transcendence.${LOCAL_IP}.nip.io:8443
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=file:/data/user.db
    volumes:
      - db-data:/data
      - uploads-data:/usr/src/app/uploads
    ports: ["3000:3000"]
    restart: unless-stopped
    networks: [ts_transcendence]

  # ─────────────────── Nginx Gateway
  nginx:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
      args:
        - DOMAIN_NAME=transcendence.${LOCAL_IP}.nip.io
    image: transcendence_gateway
    environment:
      - DOMAIN_NAME=transcendence.${LOCAL_IP}.nip.io
    depends_on: [frontend, backend]
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - uploads-data:/usr/src/app/uploads
    restart: unless-stopped
    networks: [ts_transcendence]

volumes:
  db-data:
  uploads-data:

networks:
  ts_transcendence:
    driver: bridge
