# docker-compose.yaml

version: "3.8"

services:
  # ─────────────────── Front
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    image: transcendence_frontend
    ports: ["3001:3001"] # vite preview 포트와 일치
    restart: unless-stopped
    networks: [ts_transcendence]

  # ─────────────────── Back
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    image: transcendence_backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:?set in .env}
      - DATABASE_URL=file:/data/db.sqlite
    volumes:
      - db-data:/data
      - uploads-data:/usr/src/app/uploads
    ports: ["3000:3000"]
    restart: unless-stopped
    networks: [ts_transcendence]

  # ─────────────────── Nginx Gateway
  nginx:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    image: transcendence_gateway
    depends_on: [frontend, backend]
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - uploads-data:/usr/src/app/uploads
    restart: unless-stopped
    networks: [ts_transcendence]

volumes:
  db-data:
  uploads-data:

networks:
  ts_transcendence:
    driver: bridge
