version: '3.8'

services:
    frontend:
      build:
          context: ./frontend
          dockerfile: Dockerfile
      ports:
          - "3001:3001"
      networks:
          - transcendence
      restart: unless-stopped
    backend:    # have to add env (node, database = sqlite and JWT)
      build:
        context: ./backend
        dockerfile: Dockerfile
      depends_on:
        - database
      ports:
        - "3000:3000"
      networks:
        - transcendence
      restart: unless-stopped
    
    admin:
      build: ./admin
      networks:
        - transcendence
      ports:
        - "9000:9000"
      restart: unless-stopped

    nginx:
      build: ./nginx
      ports:
        - "80:80"
      depends_on:
        - frontend
        - backend
        - admin
      networks:
        - transcendence
      restart: unless-stopped

    database:
      image: sqlite
      environment:
        SQLITE_DB: transcendence
        SQLITE_USER:  ${DB_USER:-ponguser}
        SQLITE_PASSWORD: ${DB_PASSWORD:-pongpass}
      volumes:
        - db-data:/var/lib/sqlite
      networks:
        - transcendence

volumes:
  db-data:

networks:
  transcendence:
    driver: bridge